import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, WidthType, TableRow, TableCell, Table } from 'docx';
import { saveAs } from 'file-saver';
import type { CVData } from '../types/cv';

export interface DocExportOptions {
  fileName?: string;
  includeMetadata?: boolean;
  templateStyle?: 'modern' | 'classic' | 'minimal'; // Add template awareness
}

export const generateDocCV = async (cv: CVData, options: DocExportOptions = {}) => {
  const fileName = options.fileName || 'CV.docx';
  const templateStyle = options.templateStyle || cv.templateId || 'classic';

  try {
    const doc = new Document({
      creator: 'CV Builder',
      title: `${cv.personalInfo.fullName} - Professional CV`,
      description: 'Professional CV generated by CV Builder',
      styles: {
        paragraphStyles: [
          {
            id: 'heading',
            name: 'Heading',
            basedOn: 'Normal',
            next: 'Normal',
            quickFormat: true,
            run: {
              size: 28,
              bold: true,
              color: '2563eb'
            },
            paragraph: {
              spacing: {
                after: 300,
                before: 200
              }
            }
          },
          {
            id: 'sectionHeading',
            name: 'Section Heading',
            basedOn: 'Normal',
            next: 'Normal',
            quickFormat: true,
            run: {
              size: 24,
              bold: true,
              color: '000000'
            },
            paragraph: {
              spacing: {
                after: 200,
                before: 400
              },
              border: {
                bottom: {
                  color: '000000',
                  space: 1,
                  style: BorderStyle.SINGLE,
                  size: 6
                }
              }
            }
          },
          {
            id: 'subHeading',
            name: 'Sub Heading',
            basedOn: 'Normal',
            next: 'Normal',
            quickFormat: true,
            run: {
              size: 22,
              bold: true,
              color: '374151'
            },
            paragraph: {
              spacing: {
                after: 150,
                before: 200
              }
            }
          }
        ]
      },
      sections: [
        {
          properties: {},
          children: [
            // Header with name - Template-aware alignment
            ...getHeaderForTemplate(cv.personalInfo, templateStyle),

            // Contact Information - Template-aware
            ...getContactInfoForTemplate(cv.personalInfo, templateStyle),

            // Professional Summary
            ...(cv.personalInfo.summary ? createSummarySection(cv.personalInfo.summary) : []),

            // Work Experience
            ...(cv.workExperience.length > 0 ? createWorkExperienceSection(cv.workExperience) : []),

            // Education
            ...(cv.education.length > 0 ? createEducationSection(cv.education) : []),

            // Skills - Template-aware
            ...(cv.skills.length > 0 ? getSkillsSectionForTemplate(cv.skills, templateStyle) : []),

            // Projects
            ...(cv.projects.length > 0 ? createProjectsSection(cv.projects) : []),

            // Certifications
            ...(cv.certifications.length > 0 ? createCertificationsSection(cv.certifications) : []),

            // Extracurricular
            ...(cv.extracurricular.length > 0 ? createExtracurricularSection(cv.extracurricular) : [])
          ]
        }
      ]
    });

    const blob = await Packer.toBlob(doc);

    saveAs(blob, fileName);
    return { success: true };
  } catch (error) {
    console.error('DOC generation failed:', error);
    return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
  }
};

// Default header (left-aligned for Classic and Minimal)
const createDefaultHeader = (personalInfo: CVData['personalInfo']) => {
  const headerElements = [];

  headerElements.push(
    new Paragraph({
      text: personalInfo.fullName,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.LEFT,
      spacing: {
        after: 100
      }
    })
  );

  if (personalInfo.jobTitle) {
    headerElements.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.jobTitle,
            size: 24,
            font: 'Helvetica'
          })
        ],
        alignment: AlignmentType.LEFT,
        spacing: {
          after: 200
        }
      })
    );
  }

  return headerElements;
};

// Modern header (centered like the PDF)
const createModernHeader = (personalInfo: CVData['personalInfo']) => {
  const headerElements = [];

  headerElements.push(
    new Paragraph({
      text: personalInfo.fullName,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 100
      }
    })
  );

  if (personalInfo.jobTitle) {
    headerElements.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.jobTitle,
            size: 24,
            font: 'Helvetica'
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: {
          after: 200
        }
      })
    );
  }

  return headerElements;
};

// Template-aware header function
const getHeaderForTemplate = (personalInfo: CVData['personalInfo'], templateStyle: string) => {
  switch (templateStyle) {
    case 'modern':
      return createModernHeader(personalInfo);
    case 'classic':
    case 'minimal':
    default:
      return createDefaultHeader(personalInfo);
  }
};

// Template-aware contact info function
const getContactInfoForTemplate = (personalInfo: CVData['personalInfo'], templateStyle: string) => {
  switch (templateStyle) {
    case 'minimal':
      return createMinimalContactInfo(personalInfo);
    case 'classic':
      return createClassicContactInfo(personalInfo);
    case 'modern':
      return createModernContactInfo(personalInfo);
    default:
      return createContactInfo(personalInfo);
  }
};

// Template-aware skills section function
const getSkillsSectionForTemplate = (skills: CVData['skills'], templateStyle: string) => {
  switch (templateStyle) {
    case 'minimal':
      return createCondensedSkillsSection(skills);
    case 'modern':
      return createSkillsSection(skills);
    case 'classic':
    default:
      return createSimpleSkillsSection(skills);
  }
};

// Classic contact info without tables - matches PDF layout with simple paragraphs
const createClassicContactInfo = (personalInfo: CVData['personalInfo']) => {
  const contactLines = [];

  // Left column items
  if (personalInfo.email) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Email: ${personalInfo.email}`,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 80 }
      })
    );
  }

  if (personalInfo.phone) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Phone: ${personalInfo.phone}`,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 80 }
      })
    );
  }

  if (personalInfo.website) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Website: ${personalInfo.website}`,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 80 }
      })
    );
  }

  // Right column items
  if (personalInfo.location) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Location: ${personalInfo.location}`,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 80 }
      })
    );
  }

  if (personalInfo.linkedin) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `LinkedIn: ${personalInfo.linkedin}`,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 80 }
      })
    );
  }

  if (personalInfo.github) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `GitHub: ${personalInfo.github}`,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 80 }
      })
    );
  }

  // Add spacing after contact section
  contactLines.push(
    new Paragraph({
      text: '',
      spacing: { after: 400 }
    })
  );

  return contactLines;
};

// Modern contact info - centered header with single line contact info (matches PDF exactly)
const createModernContactInfo = (personalInfo: CVData['personalInfo']) => {
  const contactInfo = [];
  const socialLinks = [];

  // Collect email and phone
  if (personalInfo.email) contactInfo.push(personalInfo.email);
  if (personalInfo.phone) contactInfo.push(personalInfo.phone);

  // Collect social links
  if (personalInfo.github) socialLinks.push(personalInfo.github);
  if (personalInfo.linkedin) socialLinks.push(personalInfo.linkedin);

  const contactElements = [];

  // First line: Email | Phone (black)
  if (contactInfo.length > 0) {
    contactElements.push(
      new Paragraph({
        children: [
          new TextRun({
            text: contactInfo.join(' | '),
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 100 }
      })
    );
  }

  // Second line: GitHub | LinkedIn (blue)
  if (socialLinks.length > 0) {
    contactElements.push(
      new Paragraph({
        children: [
          new TextRun({
            text: socialLinks.join(' | '),
            size: 20,
            font: 'Helvetica',
            color: '0000FF' // Blue color for links
          })
        ],
        spacing: { after: 300 }
      })
    );
  }

  return contactElements;
};

// Main contact info function that matches classic PDF layout exactly
const createContactInfo = (personalInfo: CVData['personalInfo']) => {
  const contactInfo = [];
  const socialLinks = [];

  // Collect email and phone
  if (personalInfo.email) contactInfo.push(personalInfo.email);
  if (personalInfo.phone) contactInfo.push(personalInfo.phone);

  // Collect social links
  if (personalInfo.github) socialLinks.push(personalInfo.github);
  if (personalInfo.linkedin) socialLinks.push(personalInfo.linkedin);

  const contactElements = [];

  // First line: Email | Phone (black)
  if (contactInfo.length > 0) {
    contactElements.push(
      new Paragraph({
        children: [
          new TextRun({
            text: contactInfo.join(' | '),
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: { after: 100 }
      })
    );
  }

  // Second line: GitHub | LinkedIn (blue)
  if (socialLinks.length > 0) {
    contactElements.push(
      new Paragraph({
        children: [
          new TextRun({
            text: socialLinks.join(' | '),
            size: 20,
            font: 'Helvetica',
            color: '0000FF' // Blue color for links
          })
        ],
        spacing: { after: 300 }
      })
    );
  }

  return contactElements;
};

// Simple contact info for classic template
const createSimpleContactInfo = (personalInfo: CVData['personalInfo']) => {
  const contactItems = [];

  if (personalInfo.email) contactItems.push(personalInfo.email);
  if (personalInfo.phone) contactItems.push(personalInfo.phone);
  if (personalInfo.location) contactItems.push(personalInfo.location);
  if (personalInfo.linkedin) contactItems.push(personalInfo.linkedin);
  if (personalInfo.website) contactItems.push(personalInfo.website);

  return [
    new Paragraph({
      children: [
        new TextRun({
          text: contactItems.join(' | '),
          size: 20
        })
      ],
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 300
      }
    })
  ];
};

// Minimal contact info for minimal template
const createMinimalContactInfo = (personalInfo: CVData['personalInfo']) => {
  const contactLines = [];

  if (personalInfo.email) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.email,
            size: 18
          })
        ],
        spacing: { after: 50 }
      })
    );
  }

  if (personalInfo.phone) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.phone,
            size: 18
          })
        ],
        spacing: { after: 50 }
      })
    );
  }

  if (personalInfo.location) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.location,
            size: 18
          })
        ],
        spacing: { after: 50 }
      })
    );
  }

  if (personalInfo.website) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.website,
            size: 18
          })
        ],
        spacing: { after: 50 }
      })
    );
  }

  if (personalInfo.linkedin) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.linkedin,
            size: 18
          })
        ],
        spacing: { after: 50 }
      })
    );
  }

  if (personalInfo.github) {
    contactLines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: personalInfo.github,
            size: 18
          })
        ],
        spacing: { after: 200 }
      })
    );
  }

  return contactLines;
};

// Simple skills section for classic template
const createSimpleSkillsSection = (skills: CVData['skills']) => [
  new Paragraph({
    text: 'SKILLS',
    style: 'sectionHeading'
  }),
  new Paragraph({
    children: [
      new TextRun({
        text: skills.filter(skill => skill.name).map(skill => skill.name).join(' • '),
        size: 20
      })
    ],
    spacing: {
      after: 200
    }
  })
];

// Condensed skills section for minimal template
const createCondensedSkillsSection = (skills: CVData['skills']) => [
  new Paragraph({
    text: 'Skills',
    style: 'sectionHeading'
  }),
  new Paragraph({
    children: [
      new TextRun({
        text: skills.filter(skill => skill.name).map(skill => skill.name).join(', '),
        size: 18
      })
    ],
    spacing: {
      after: 150
    }
  })
];

const createSummarySection = (summary: string) => [
  new Paragraph({
    text: 'PROFESSIONAL SUMMARY',
    style: 'sectionHeading'
  }),
  new Paragraph({
    children: [
      new TextRun({
        text: summary,
        size: 20,
        font: 'Helvetica'
      })
    ],
    spacing: {
      after: 300
    }
  })
];

const createWorkExperienceSection = (workExperience: CVData['workExperience']) => [
  new Paragraph({
    text: 'PROFESSIONAL EXPERIENCE',
    style: 'sectionHeading'
  }),
  ...workExperience.flatMap(exp => {
    const startDate = exp.startDate;
    const endDate = exp.isCurrentJob ? 'Present' : (exp.endDate || '');
    const dateRange = endDate ? `${startDate} - ${endDate}` : startDate;

    // Company name only (without location)
    const companyText = exp.company;

    return [
      // Position (bold) - matches PDF
      new Paragraph({
        children: [
          new TextRun({
            text: exp.position,
            bold: true,
            size: 22,
            font: 'Helvetica'
          })
        ],
        spacing: {
          before: 200
        }
      }),
      // Date range on separate line - right aligned to match PDF
      new Paragraph({
        children: [
          new TextRun({
            text: dateRange,
            size: 18,
            font: 'Helvetica'
          })
        ],
        alignment: AlignmentType.RIGHT,
        spacing: {
          after: 50
        }
      }),
      // Company and location
      new Paragraph({
        children: [
          new TextRun({
            text: companyText,
            italics: true,
            size: 20,
            font: 'Helvetica'
          })
        ],
        spacing: {
          after: 100
        }
      }),
      // Description if exists
      ...(exp.description ? [
        new Paragraph({
          text: exp.description,
          spacing: {
            after: 100
          }
        })
      ] : []),
      // Bullet points with proper indentation
      ...exp.bulletPoints.map((bullet) => {
        // Ensure we have a valid bullet point object
        if (!bullet || typeof bullet !== 'object') {
          console.warn('Invalid bullet point:', bullet);
          return new Paragraph({
            text: `• ${String(bullet)}`,
            spacing: { before: 50 }
          });
        }

        // Handle bullet point with proper text extraction
        const bulletText = bullet.text || '';
        if (!bulletText) {
          console.warn('Empty bullet point text:', bullet);
          return new Paragraph({
            text: '• [Empty bullet point]',
            spacing: { before: 50 }
          });
        }

        return new Paragraph({
          text: `• ${bulletText}`,
          spacing: {
            before: 50
          }
        });
      })
    ];
  })
];

const createEducationSection = (education: CVData['education']) => [
  new Paragraph({
    text: 'EDUCATION',
    style: 'sectionHeading'
  }),
  ...education.flatMap(edu => [
    new Paragraph({
      children: [
        new TextRun({
          text: edu.degree,
          bold: true,
          size: 22,
          font: 'Helvetica'
        })
      ],
      spacing: {
        before: 200
      }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `${edu.institution} | `,
          italics: true
        }),
        new TextRun({
          text: `${edu.startDate} - ${edu.endDate || 'Present'}`,
          italics: true
        }),
        ...(edu.gpa ? [
          new TextRun({
            text: ` | GPA: ${edu.gpa}`,
            italics: true
          })
        ] : [])
      ]
    }),
    ...(edu.description ? [
      new Paragraph({
        text: edu.description,
        spacing: {
          after: 150
        }
      })
    ] : [])
  ])
];

const createSkillsSection = (skills: CVData['skills']) => {
  const skillsByCategory = skills.reduce((acc, skill) => {
    // Default category if undefined
    const category = skill.category || 'General Skills';
    if (!acc[category]) {
      acc[category] = [];
    }
    // Ensure skill.name exists
    if (skill.name) {
      acc[category].push(skill.name);
    }
    return acc;
  }, {} as Record<string, string[]>);

  return [
    new Paragraph({
      text: 'SKILLS',
      style: 'sectionHeading'
    }),
    ...Object.entries(skillsByCategory).map(([category, skillNames]) =>
      new Paragraph({
        children: [
          new TextRun({
            text: `${category}: `,
            bold: true
          }),
          new TextRun({
            text: skillNames.join(', ')
          })
        ],
        spacing: {
          after: 100
        }
      })
    )
  ];
};

const createProjectsSection = (projects: CVData['projects']) => [
  new Paragraph({
    text: 'PROJECTS',
    style: 'sectionHeading'
  }),
  ...projects.flatMap(project => [
    new Paragraph({
      children: [
        new TextRun({
          text: project.name,
          bold: true,
          size: 22
        })
      ],
      spacing: {
        before: 200
      }
    }),
    ...(project.url ? [
      new Paragraph({
        children: [
          new TextRun({
            text: `${project.url}`,
            italics: true
          })
        ]
      })
    ] : []),
    new Paragraph({
      text: project.description,
      spacing: {
        after: 100
      }
    }),
    ...(project.technologies && project.technologies.length > 0 ? [
      new Paragraph({
        children: [
          new TextRun({
            text: 'Technologies: ',
            bold: true
          }),
          new TextRun({
            text: project.technologies.join(', ')
          })
        ]
      })
    ] : [])
  ])
];

const createCertificationsSection = (certifications: CVData['certifications']) => [
  new Paragraph({
    text: 'CERTIFICATIONS',
    style: 'sectionHeading'
  }),
  ...certifications.map(cert =>
    new Paragraph({
      children: [
        new TextRun({
          text: cert.name,
          bold: true
        }),
        new TextRun({
          text: ` - ${cert.issuer}`,
          italics: true
        }),
        ...(cert.date ? [
          new TextRun({
            text: ` (${cert.date})`,
            italics: true
          })
        ] : [])
      ],
      spacing: {
        after: 100
      }
    })
  )
];

const createExtracurricularSection = (extracurricular: CVData['extracurricular']) => [
  new Paragraph({
    text: 'EXTRACURRICULAR ACTIVITIES',
    style: 'sectionHeading'
  }),
  ...extracurricular.flatMap(activity => [
    new Paragraph({
      children: [
        new TextRun({
          text: activity.title,
          bold: true,
          size: 22
        })
      ],
      spacing: {
        before: 200
      }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `${activity.organization} | `,
          italics: true
        }),
        new TextRun({
          text: `${activity.startDate} - ${activity.endDate || 'Present'}`,
          italics: true
        })
      ]
    }),
    new Paragraph({
      text: activity.description,
      spacing: {
        after: 150
      }
    })
  ])
];
